### ISSUE TITLE
Feature: demo upload file to see how it works

### ISSUE THREAD

**Issue by dbkaplun** [thlorenz/turbolizer#1]

**Comment by thlorenz** [comment]
I agree that'd be nice, but then we'd either have to include the data it in the package you install or inline it somehow in the version I'm hosting on github pages.
I'd prefer the latter, but then I'd have to edit the files from the v8 repo even more and I wanna keep the diffs as little as possible, to make updating to new versions easier.

I think a better option would be to host an example outside of this repo, i.e. a blog or another repo.
All you have to do is take what's here and edit the `lib/client-loader.js` to inline the data instead of fetching it. Then you throw that up somewhere, i.e. host on gh-pages and I can link to it from this repo.
